### ISSUE TITLE
autolabel:

### ISSUE THREAD

**Issue by gitwdel** [kaxil/boring-cyborg#17]
autolabel:
  - label: schema
    files: ['database/migrations/*']

  - label: 'Cool Project'
    files: ['app/CoolProject/**', 'app/CoolProject/*']
    titleRegex: '.*COOL\-.*'

_Originally posted by @gitwdel in https://github.com/kaxil/boring-cyborg/issues/16#issuecomment-600430450_

**Comment by reececomo** [comment]
Why did you copy and paste the schema I suggested and make a duplicate issue?
