### ISSUE TITLE
Is there a way to act when a file is _not_ included?

### ISSUE THREAD

**Issue by bobjacobsen** [kaxil/boring-cyborg#22]
The JMRI[https://github.com/JMRI/JMRI] build process includes a `current-draft-note` file that's meant to accumulate text for the eventual release note.  

Is there a way to label PRs that _don't_ include an update to that file?  That would serve as an automated reminder that people should please include something about their PR in that file.

**Comment by kaxil** [comment]
Not currently with boring-cyborg. But you could use Mergeable https://github.com/mergeability/mergeable to add some rules.
