### ISSUE TITLE
Private repos

### ISSUE THREAD

**Issue by clarkd** [kaxil/boring-cyborg#6]
Does this work for private repos?

We've added the extension and the config file but nothing seems to be happening?

**Comment by kaxil** [comment]
@clarkd 

For the app to work on Private Repo, we have requested adding read-only permission on a single file ".github/boring-cyborg.yml", please grant the additional permission and it should work on **Private Repo** too

cc @reececomo

**Comment by kaxil** [comment]
@clarkd  Any luck after your approved the updated permission request?

**Comment by reececomo** [comment]
@kaxil it works perfectly on our private repos now 👍

Not sure if you're open to contributors, but would love to customise the title validation status (like a custom error message or title for that), and to be able to set it to _always_ use the PR title.

**Comment by kaxil** [comment]
> @kaxil it works perfectly on our private repos now 👍
> 
> Not sure if you're open to contributors, but would love to customise the title validation status (like a custom error message or title for that), and to be able to set it to _always_ use the PR title.

Of course, very open to contributions :) I spend most of my time contributing to  https://github.com/apache/airflow and created the bot to implement some features we wanted and to generalize it so that anyone can use it too. 

Please feel free to raise PR as I would love contributions :)

**Comment by marceloalmeida** [comment]
@kaxil this issue still persists on private repositories on the "PR/Branch Up-To-Date Checker" feature. Any hints?

**Comment by kaxil** [comment]
> @kaxil this issue still persists on private repositories on the "PR/Branch Up-To-Date Checker" feature. Any hints?

It should work fine as long as you give permissions to the App

**Comment by marceloalmeida** [comment]
> > @kaxil this issue still persists on private repositories on the "PR/Branch Up-To-Date Checker" feature. Any hints?
> 
> It should work fine as long as you give permissions to the App

The app has the following permissions ![image](https://user-images.githubusercontent.com/11047924/147008501-aada67f9-f618-4cc5-8ed6-bd62e8f1ac2c.png)
 Is there any way to give extra permissions?

**Comment by kaxil** [comment]
hmm that is so weird, I used it on one of my private repos and know few folks who do the same.  I will try again over the weekend to see if something changed

**Comment by kaxil** [comment]
I just tried it on a private repo, installed the app and worked fine. Screenshot below:

![image](https://user-images.githubusercontent.com/8811558/147513620-07a6f511-8a0d-474d-8585-4b65f6af5393.png)

**Comment by marceloalmeida** [comment]
I have `labelPRBasedOnFilePath` working the private repository, but unfortunately, the `checkUpToDate` isn't working, only works on public repositories.

Here it goes a piece of the `.github/boring-cyborg.yml` @kaxil - The current repository that I'm using for tests is this one - https://github.com/marceloalmeida/test-boring (right now is public)
```
checkUpToDate:
  # The default branch is "master", change the branch if you want to check against a different target branch  
  targetBranch: main
  files:
    - airflow/migrations/*
    - airflow/migrations/**/*
    - airflow/alembic.ini
```
