### ISSUE TITLE
verifyTitles suddenly fail to fire

### ISSUE THREAD

**Issue by SbloodyS** [kaxil/boring-cyborg#78]
`verifyTitles` suddenly fail to fire in my private repository a few hours ago.  The logo for the test results didn't even appear. But the `labelPRBasedOnFilePath` works fine. 
How can I solve it? Is there any log I can debug? Thanks.

**Comment by kaxil** [comment]
Huh, that seems strange, I will check later in the next couple of days. I haven't updated the app so there should be no change.

**Comment by kaxil** [comment]
I wasn't able to find any issues, do this still persist on your end @SbloodyS ?

**Comment by SbloodyS** [comment]
> I wasn't able to find any issues, do this still persist on your end @SbloodyS ?

It's back to normal now. I don't know what happened in those days. Thanks for your help.
